/**
 * Swiss Resilience Navigator 2.5 — Pan-Swiss Data Engine
 * Module: pan_swiss_data.js
 * 
 * Aggregates:
 * 1. 26 Cantonal Social Housing Rent Ceilings (EVAM, Hospice Général, AOZ, GSI, WSU, LAPS, etc.)
 * 2. CH-ISCO-19 Profession Classifier with Quad-lingual titles & Stellenmeldepflicht warnings
 * 3. Art. 262 CO Subletting & Furniture Surcharge Rules
 * 4. Quad-lingual Disclaimers & Association in Formation status (Art. 60-79 CC)
 */

export const CANTONS_26 = [
  {
    code: "AG",
    name: "Aargau",
    authority: "MIKA / SDA / Kommunale Sozialdienste",
    persons_1_chf: 950,
    persons_2_chf: 1250,
    persons_3_chf: 1450,
    persons_4_chf: 1650,
    persons_5plus_chf: 1900,
    rent_type: "net",
    charges_coverage: "charges nettes; фактичні комунальні окремо, громади встановлюють власні норми",
    legal_sources: "SPG AG SAR 861.100; Positionspapier VAGS Mietzinsrichtlinien"
  },
  {
    code: "AI",
    name: "Appenzell Innerrhoden",
    authority: "Gesundheits- und Sozialdepartement / Asylkommission",
    persons_1_chf: 850,
    persons_2_chf: 1150,
    persons_3_chf: 1350,
    persons_4_chf: 1525,
    persons_5plus_chf: 1725,
    rent_type: "brut",
    charges_coverage: "charges comprises; паушальні брутто-ліміти з річною звіркою",
    legal_sources: "Sozialhilfegesetz AI GS 850.000"
  },
  {
    code: "AR",
    name: "Appenzell Ausserrhoden",
    authority: "Departement Soziales / Gemeindedienste",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1625,
    persons_5plus_chf: 1825,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні за договором",
    legal_sources: "SHG AR bGS 851.1"
  },
  {
    code: "BE",
    name: "Bern",
    authority: "GSI Bern / BKSE / Regionale Partner Asyl",
    persons_1_chf: 1000,
    persons_2_chf: 1350,
    persons_3_chf: 1550,
    persons_4_chf: 1750,
    persons_5plus_chf: 1950,
    rent_type: "net",
    charges_coverage: "charges nettes; Nebenkosten nach Vertrag + ggf. Pauschale 50 CHF",
    legal_sources: "SHG BE BSG 860.1; SAFG BE BSG 861.1; BKSE-Handbuch"
  },
  {
    code: "BL",
    name: "Basel-Landschaft",
    authority: "VSD / KIGA / Asylkoordination",
    persons_1_chf: 950,
    persons_2_chf: 1250,
    persons_3_chf: 1450,
    persons_4_chf: 1650,
    persons_5plus_chf: 1850,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні оплачуються окремо за рахунками",
    legal_sources: "SHG BL SGS 850"
  },
  {
    code: "BS",
    name: "Basel-Stadt",
    authority: "WSU Basel-Stadt / Sozialhilfe Basel",
    persons_1_chf: 880,
    persons_2_chf: 1210,
    persons_3_chf: 1390,
    persons_4_chf: 1675,
    persons_5plus_chf: 1925,
    rent_type: "brut",
    charges_coverage: "brut base + фактичне опалення (Heizkosten separat)",
    legal_sources: "SHG BS SG 852.100; Mietzinsrichtlinien WSU BS"
  },
  {
    code: "FR",
    name: "Fribourg",
    authority: "ORS Service / DSAS Fribourg",
    persons_1_chf: 900,
    persons_2_chf: 1150,
    persons_3_chf: 1350,
    persons_4_chf: 1550,
    persons_5plus_chf: 1750,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні покриваються за договором",
    legal_sources: "LASOC FR RSF 831.0.1"
  },
  {
    code: "GE",
    name: "Genève",
    authority: "Hospice Général Genève",
    persons_1_chf: 1465,
    persons_2_chf: 1735,
    persons_3_chf: 1925,
    persons_4_chf: 2100,
    persons_5plus_chf: 2250,
    rent_type: "brut",
    charges_coverage: "charges comprises; або 1100-1800 net + charges réelles",
    legal_sources: "LIASI GE J 4 06; Barèmes d'aide financière Hospice Général"
  },
  {
    code: "GL",
    name: "Glarus",
    authority: "Hauptabteilung Soziales / Asylwesen Glarus",
    persons_1_chf: 850,
    persons_2_chf: 1100,
    persons_3_chf: 1300,
    persons_4_chf: 1500,
    persons_5plus_chf: 1700,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні окремо",
    legal_sources: "SHG GL GS VIII B/1"
  },
  {
    code: "GR",
    name: "Graubünden",
    authority: "Sozialamt Graubünden / Fachstelle Asyl",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; регіональна диференціація (Engadin vs Chur)",
    legal_sources: "UGSH GR BR 546.000"
  },
  {
    code: "JU",
    name: "Jura",
    authority: "AJAS (Association jurassienne d'accueil des migrants)",
    persons_1_chf: 800,
    persons_2_chf: 1050,
    persons_3_chf: 1250,
    persons_4_chf: 1450,
    persons_5plus_chf: 1650,
    rent_type: "net",
    charges_coverage: "charges nettes; опалення окремо",
    legal_sources: "LAS Jura RSJU 850.11"
  },
  {
    code: "LU",
    name: "Luzern",
    authority: "DISG / Dienststelle Asyl- und Flüchtlingswesen (DAF)",
    persons_1_chf: 950,
    persons_2_chf: 1250,
    persons_3_chf: 1450,
    persons_4_chf: 1650,
    persons_5plus_chf: 1850,
    rent_type: "net",
    charges_coverage: "charges nettes; міські ліміти вищі на 10%",
    legal_sources: "SHG LU SRL 892; DAF Richtlinien"
  },
  {
    code: "NE",
    name: "Neuchâtel",
    authority: "Service des migrations / SASIS Neuchâtel",
    persons_1_chf: 850,
    persons_2_chf: 1100,
    persons_3_chf: 1300,
    persons_4_chf: 1500,
    persons_5plus_chf: 1700,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні за договором",
    legal_sources: "LASP NE RSN 831.0"
  },
  {
    code: "NW",
    name: "Nidwalden",
    authority: "Amt für Asyl und Flüchtlinge Nidwalden",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; фактичні витрати за договором",
    legal_sources: "SHG NW NG 721.1"
  },
  {
    code: "OW",
    name: "Obwalden",
    authority: "Sozialamt Obwalden / Asylkoordination",
    persons_1_chf: 880,
    persons_2_chf: 1180,
    persons_3_chf: 1380,
    persons_4_chf: 1580,
    persons_5plus_chf: 1780,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні окремо",
    legal_sources: "SHG OW GDB 810.1"
  },
  {
    code: "SG",
    name: "St. Gallen",
    authority: "Departement des Innern / TISG St. Gallen",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; TISG норми для біженців",
    legal_sources: "SHG SG sGS 381.1; TISG Handbuch"
  },
  {
    code: "SH",
    name: "Schaffhausen",
    authority: "Sozialamt Kanton Schaffhausen / Fachstelle Asyl",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні за рахунками",
    legal_sources: "SHG SH SHR 850.100"
  },
  {
    code: "SO",
    name: "Solothurn",
    authority: "Amt für Gesellschaft und Soziales (AGS)",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні покриваються за договором",
    legal_sources: "SHG SO BGS 831.1"
  },
  {
    code: "SZ",
    name: "Schwyz",
    authority: "Amt für Gesundheit und Soziales Schwyz",
    persons_1_chf: 950,
    persons_2_chf: 1250,
    persons_3_chf: 1450,
    persons_4_chf: 1650,
    persons_5plus_chf: 1850,
    rent_type: "net",
    charges_coverage: "charges nettes; окремі норми для Ausserschwyz",
    legal_sources: "SHG SZ SRSZ 384.100"
  },
  {
    code: "TG",
    name: "Thurgau",
    authority: "Sozialamt Kanton Thurgau / Peregrina-Stiftung",
    persons_1_chf: 900,
    persons_2_chf: 1200,
    persons_3_chf: 1400,
    persons_4_chf: 1600,
    persons_5plus_chf: 1800,
    rent_type: "net",
    charges_coverage: "charges nettes; паушальні комунальні або факт",
    legal_sources: "SHG TG RB 850.1"
  },
  {
    code: "TI",
    name: "Ticino",
    authority: "DSS / Ufficio dei richiedenti l'asilo e rifugiati (LAPS)",
    persons_1_chf: 800,
    persons_2_chf: 1100,
    persons_3_chf: 1350,
    persons_4_chf: 1450,
    persons_5plus_chf: 1500,
    rent_type: "net",
    charges_coverage: "charges nettes; flat cap максимум 1500 CHF для великих родин",
    legal_sources: "LAPS TI RL 871.100; Regolamento d'applicazione LAPS"
  },
  {
    code: "UR",
    name: "Uri",
    authority: "Amt für Arbeit und Soziales Uri / SRK Uri",
    persons_1_chf: 850,
    persons_2_chf: 1100,
    persons_3_chf: 1300,
    persons_4_chf: 1500,
    persons_5plus_chf: 1700,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні окремо",
    legal_sources: "SHG UR RB 30.2101"
  },
  {
    code: "VD",
    name: "Vaud",
    authority: "EVAM (Établissement vaudois d'accueil des migrants)",
    persons_1_chf: 1050,
    persons_2_chf: 1180,
    persons_3_chf: 1350,
    persons_4_chf: 1650,
    persons_5plus_chf: 2100,
    rent_type: "net",
    charges_coverage: "charges nettes; комунальні сплачуються EVAM окремо за фактом",
    legal_sources: "LAsi Art. 80-84; LAS Vaud Art. 34; Directives EVAM"
  },
  {
    code: "VS",
    name: "Valais",
    authority: "Service de l'action sociale (SAS) / Croix-Rouge Valais",
    persons_1_chf: 850,
    persons_2_chf: 1100,
    persons_3_chf: 1300,
    persons_4_chf: 1500,
    persons_5plus_chf: 1700,
    rent_type: "net",
    charges_coverage: "charges nettes; різниця між Bas-Valais та Haut-Valais",
    legal_sources: "LIAS VS RS 850.1"
  },
  {
    code: "ZG",
    name: "Zug",
    authority: "Direktion des Innern / Soziale Dienste Asyl Zug",
    persons_1_chf: 1100,
    persons_2_chf: 1400,
    persons_3_chf: 1650,
    persons_4_chf: 1850,
    persons_5plus_chf: 2100,
    rent_type: "net",
    charges_coverage: "charges nettes; найвищі орендні ставки в центральній Швейцарії",
    legal_sources: "SHG ZG BGS 861.1"
  },
  {
    code: "ZH",
    name: "Zürich",
    authority: "AOZ (Asyl-Organisation Zürich) / Sozialamt Stadt Zürich",
    persons_1_chf: 1400,
    persons_2_chf: 1650,
    persons_3_chf: 1800,
    persons_4_chf: 1950,
    persons_5plus_chf: 2050,
    rent_type: "brut",
    charges_coverage: "charges comprises; молодіжні WG ліміт 800 CHF",
    legal_sources: "SHG ZH LS 851.1; Richtlinien für die Sozialhilfe Stadt Zürich"
  }
];

export const PROFESSIONS_ISCO = [
  {
    sector: "HOSP",
    sector_uk: "Готельно-ресторанний бізнес",
    sector_fr: "Hôtellerie-Restauration",
    sector_de: "Gastgewerbe & Hotellerie",
    sector_it: "Alberghiero e Ristorazione",
    isco: "5120",
    title_uk: "Кухар",
    title_fr: "Cuisinier / Cuisinière",
    title_de: "Koch / Köchin",
    title_it: "Cuoco / Cuoca",
    qual_levels: ["Sans diplôme", "AFP/EBA", "CFC/EFZ", "Diplôme/HF", "Tertiaire"],
    stellenmeldepflicht: true,
    salary_range: "3 713 – 5 200 CHF",
    key_regulation: "CCNT/L-GAV; Art. 21a LEI"
  },
  {
    sector: "HOSP",
    sector_uk: "Готельно-ресторанний бізнес",
    sector_fr: "Hôtellerie-Restauration",
    sector_de: "Gastgewerbe & Hotellerie",
    sector_it: "Alberghiero e Ristorazione",
    isco: "5131",
    title_uk: "Офіціант / Фахівець ресторанного сервісу",
    title_fr: "Spécialiste de service / Serveur",
    title_de: "Restaurantfachmann / -frau",
    title_it: "Cameriere / Cameriera di sala",
    qual_levels: ["Sans diplôme", "AFP/EBA", "CFC/EFZ", "Tertiaire"],
    stellenmeldepflicht: true,
    salary_range: "3 713 – 5 000 CHF",
    key_regulation: "CCNT/L-GAV; Art. 21a LEI"
  },
  {
    sector: "HOSP",
    sector_uk: "Готельно-ресторанний бізнес",
    sector_fr: "Hôtellerie-Restauration",
    sector_de: "Gastgewerbe & Hotellerie",
    sector_it: "Alberghiero e Ristorazione",
    isco: "9412",
    title_uk: "Помічник кухаря / Кухонний робітник",
    title_fr: "Aide de cuisine / Plongeur",
    title_de: "Küchenhilfe / Spüler",
    title_it: "Aiuto cucina / Lavapiatti",
    qual_levels: ["Sans diplôme", "Progresso", "AFP/EBA"],
    stellenmeldepflicht: true,
    salary_range: "3 713 – 4 100 CHF",
    key_regulation: "CCNT/L-GAV"
  },
  {
    sector: "HOSP",
    sector_uk: "Готельно-ресторанний бізнес",
    sector_fr: "Hôtellerie-Restauration",
    sector_de: "Gastgewerbe & Hotellerie",
    sector_it: "Alberghiero e Ristorazione",
    isco: "4224",
    title_uk: "Адміністратор готелю / Рецепціоніст",
    title_fr: "Réceptionniste d’hôtel",
    title_de: "Hotel-Rezeptionist/in",
    title_it: "Receptionist d’albergo",
    qual_levels: ["Aide", "CFC/EFZ", "Diplôme/HF"],
    stellenmeldepflicht: true,
    salary_range: "3 900 – 5 500 CHF",
    key_regulation: "CCNT/L-GAV; Art. 21a LEI"
  },
  {
    sector: "CONST",
    sector_uk: "Будівництво та оздоблювальні роботи",
    sector_fr: "Construction & Bâtiment",
    sector_de: "Baugewerbe",
    sector_it: "Edilizia e Costruzioni",
    isco: "7112",
    title_uk: "Муляр / Будівельник",
    title_fr: "Maçon",
    title_de: "Maurer/in",
    title_it: "Muratore",
    qual_levels: ["Manœuvre", "AFP/EBA", "CFC/EFZ", "Contremaître"],
    stellenmeldepflicht: true,
    salary_range: "4 700 – 6 200 CHF",
    key_regulation: "LMV / CNM Construction; Art. 21a LEI"
  },
  {
    sector: "CONST",
    sector_uk: "Будівництво та оздоблювальні роботи",
    sector_fr: "Construction & Bâtiment",
    sector_de: "Baugewerbe",
    sector_it: "Edilizia e Costruzioni",
    isco: "7115",
    title_uk: "Тесляр / Столяр",
    title_fr: "Charpentier / Menuisier",
    title_de: "Zimmermann / Schreiner",
    title_it: "Carpentiere / Falegname",
    qual_levels: ["Aide", "AFP/EBA", "CFC/EFZ"],
    stellenmeldepflicht: true,
    salary_range: "4 600 – 6 000 CHF",
    key_regulation: "CCT Menuiserie-Charpente; Art. 21a LEI"
  },
  {
    sector: "CONST",
    sector_uk: "Будівництво та оздоблювальні роботи",
    sector_fr: "Construction & Bâtiment",
    sector_de: "Baugewerbe",
    sector_it: "Edilizia e Costruzioni",
    isco: "9313",
    title_uk: "Різноробочий на будівництві",
    title_fr: "Manœuvre en bâtiment",
    title_de: "Bauarbeiter ohne Fachausbildung",
    title_it: "Manovale edile",
    qual_levels: ["Sans diplôme"],
    stellenmeldepflicht: true,
    salary_range: "4 300 – 4 700 CHF",
    key_regulation: "LMV / CNM Classe C; Art. 21a LEI"
  },
  {
    sector: "HEALTH",
    sector_uk: "Охорона здоров'я та догляд",
    sector_fr: "Santé & Soins",
    sector_de: "Gesundheits- & Sozialwesen",
    sector_it: "Sanità e Assistenza",
    isco: "5321",
    title_uk: "Помічник з догляду / Санітар",
    title_fr: "Aide-soignant / Auxiliaire de santé",
    title_de: "Pflegeassistent/in / Pflegehilfe SRK",
    title_it: "Aiutante di cura / Assistente CRS",
    qual_levels: ["Formation Croix-Rouge (CRS)", "AFP/EBA ASA", "CFC ASSC"],
    stellenmeldepflicht: false,
    salary_range: "4 100 – 5 100 CHF",
    key_regulation: "CCT Santé / Dérogation pénurie (Fachkräftemangel)"
  },
  {
    sector: "LOG",
    sector_uk: "Логістика та складування",
    sector_fr: "Logistique & Transport",
    sector_de: "Logistik & Lager",
    sector_it: "Logistica e Magazzino",
    isco: "4321",
    title_uk: "Працівник складу / Логіст",
    title_fr: "Logisticien / Cariste",
    title_de: "Logistiker/in / Staplerfahrer",
    title_it: "Logista / Carrellista",
    qual_levels: ["Permis cariste SUVA", "AFP/EBA", "CFC/EFZ"],
    stellenmeldepflicht: false,
    salary_range: "4 000 – 5 200 CHF",
    key_regulation: "ASFL SVBL Convention"
  }
];

export const SUBLEASE_LEGAL_FRAMEWORK = {
  article: "Art. 262 CO (Code des obligations suisse)",
  imperative_right: true,
  max_furniture_surcharge_percent: 20.0,
  min_furniture_surcharge_percent: 10.0,
  tax_exempt_reimbursement: true,
  notice_period_furnished_room: "2 semaines pour la fin d'un mois (Art. 266e CO)",
  notice_period_whole_flat: "3 mois pour les termes locaux (Art. 266c CO)",
  collective_rc_insurance_coverage_chf: 5000000
};

export const BETA_TRANSPARENCY_DECLARATION = {
  association_status: {
    fr: "Association Swiss Resilience en cours de constitution (Art. 60–79 CC Suisse)",
    de: "Verein Swiss Resilience in Gründung (Art. 60–79 ZGB)",
    it: "Associazione Swiss Resilience in costituzione (Art. 60–79 CC Svizzero)",
    uk: "Асоціація Swiss Resilience на стадії створення (ст. 60–79 Цивільного кодексу Швейцарії)"
  },
  non_agency_statement: {
    fr: "Cette plateforme ne constitue pas une agence de placement privé au sens de la LSE (RS 292.11, Art. 9). Aucun frais n'est perçu auprès des candidats.",
    de: "Diese Plattform ist keine private Arbeitsvermittlungsagentur im Sinne des AVG (SR 292.11, Art. 9). Keine Vermittlungsgebühren für Stellensuchende.",
    it: "Questa piattaforma non è un'agenzia di collocamento privato ai sensi della LCol (RS 292.11, Art. 9). Nessun compenso richiesto ai candidati.",
    uk: "Платформа не є агентством з працевлаштування у розумінні закону LSE (ст. 9). Послуги для кандидатів є повністю безкоштовними."
  },
  beta_pricing_note: {
    fr: "Tarifs commerciaux suspendus pendant la phase Bêta publique. Inscription et accès 100% gratuits. Seuls les dons volontaires sont acceptés.",
    de: "Kommerzielle Tarife während der öffentlichen Beta-Phase ausgesetzt. 100% kostenlose Nutzung. Es werden nur freiwillige Spenden akzeptiert.",
    it: "Tariffe commerciali sospese durante la fase Beta pubblica. Accesso gratuito al 100%. Sono accettate solo donazioni volontarie.",
    uk: "Комерційні тарифи тимчасово вимкнено на період публічної бета-версії. Користування безкоштовне. Приймаються лише добровільні пожертви."
  }
};
